name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install
      - name: Build frontend
        run: cd frontend && npm run build
      - name: Deploy to Staging
        run: |
          ssh user@staging-server 'cd /path/to/backend && git pull && npm install && pm2 restart backend'
          ssh user@staging-server 'cd /path/to/frontend/build && serve -s .'
